config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :movies

  get 'more_movies', to: 'movies#more_movies', as: :more_movies

  resources :sessions, only: [:new, :create]

  resources :users

  get 'user_top_posts', to: 'users#top_posts', as: :user_top_posts
  get 'user_new_posts', to: 'users#new_posts', as: :user_new_posts

  resources :comments

  get 'upvote', to: 'comments#upvote', as: :upvote

  resources :home, only: [:index]

  get 'top_posts', to: 'home#top_posts', as: :top_posts
  get 'my_posts', to: 'home#my_posts', as: :my_posts
  get 'new_posts', to: 'home#new_posts', as: :new_posts
  get 'my_correct_guesses', to: 'home#my_correct_guesses', as: :my_correct_guesses

  resources :guesses

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user
  has_many :guesses

  stores_emoji_characters :body

  scope :user_comments, ->(user_id) { where "user_id = ?", user_id }
  scope :guessed_correctly, ->(user_id) { joins(:guesses).where('guesses.user_id = ? and guesses.correct = ?', user_id, true) }

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end

  def correct_guesses
    correct = 0
    guesses.each do |guess|
      correct += 1 if guess.correct == true
    end
    return correct
  end

  def incorrect_guesses
    incorrect = 0
    guesses.each do |guess|
      incorrect += 1 if guess.correct == false
    end
    return incorrect
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    binding.pry
    @comment = Comment.find(params[:id])
    @movie = Movie.find(@comment.commentable_id) if @comment
  end

  def create

    @comment_hash = params[:comment]
    @obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
        # Not implemented: check to see whether the user has permission to create a comment on this object
    @comment = Comment.build_from(@obj, current_user.id, @comment_hash[:body])
    if @comment.save
      @guess = Guess.new
      @comments = Comment.all.order("created_at desc").take(10)
      render 'create'
    else
      render :js => "alert_box.show('Something went wrong, please try again.');"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to :back
    else
      render :js => "alert_box.show('Something went wrong, please try again.');"
    end
  end

  def upvote
    @comment = Comment.find(params[:c_id])
    @user = User.find(params[:u_id])

    if @comment.find_votes_for(:voter => @user).present?

      @comment.unliked_by @user
    else

      @comment.liked_by @user
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_list.html.erb
<div class="emovi-list-partial animated fadeIn">
  <% comments.each do |c|  %>
    <div class="small-9 columns small-centered">
      <article class="comment-box">
        <div class="comment-<%= c.id %>">
          <%= render 'comments/upvote_button', comment: c %>
          <%= link_to comment_path(c) do %>
            <h1 class="comment-body"><%= c.body %></h1>
          <% end %>
          <%= link_to user_path(c.user) do %>
            <span class="comment-user"><i class="fa fa-user"></i> <%= c.user.username %></span>
          <% end %>
          <div class="correct-incorrect-scores">
            <span class="correct-guesses"><%= c.correct_guesses %> <i class="fa fa-check"></i></span> |
            <span class="incorrect-guesses"><%= c.incorrect_guesses %> <i class="fa fa-close"></i></span>
          </div>
          <% if logged_in? && current_user != c.user %>
            <% if !@correct_guess %>
              <%= form_for guess, remote: true, html: {class: "guess-form-#{c.id}"} do |f| %>
                <%= f.text_field :body, :placeholder  =>  "Guess The Movie" %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.hidden_field :comment_id, :value => c.id %>
                <%= f.button :submit, data: { disable_with: "Submitting..." }, class: "radius" %>
              <% end %>
            <% else %>
              <button>Correct</button>
            <% end %>
          <% end %>
        </div>
      </article>
    </div>
    <hr>
  <% end %>
</div>

app/views/comments/_upvote_button.html.erb
<div class='upvote-button-partial-<%= comment.id %>'>
  <% if logged_in? %>
    <% unless comment.find_votes_for(:voter => current_user).present? %>
      <%= link_to upvote_path(params: { c_id: comment.id, u_id: current_user.id }), remote: true do %>
        <span>
          <i class="fa fa-arrow-circle-up fa-3x animated fadeIn"></i>
          <%= comment.get_upvotes.size %>
        </span>
      <% end %>
    <% else %>
      <%= link_to upvote_path(params: { c_id: comment.id, u_id: current_user.id }), remote: true do %>
        <span>
          <i class="fa fa-arrow-circle-up fa-3x animated fadeIn" style="color:gold;"></i>
          <%= comment.get_upvotes.size %>
        </span>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to new_user_path do %>
      <span>
        <i class="fa fa-arrow-circle-up fa-3x"></i>
        <%= comment.get_upvotes.size %>
      </span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#button-form-<%= @comment.commentable_id %>').addClass('anmited fadeOut hide');
var container = $('.emovi-list-partial');
container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments, guess: @guess %>');

app/views/comments/show.html.erb
<div class="row">
  <div class="small-12 small-centered text-center">
    <h1 class="text-centered"><%= @movie.title %></h1>
    <article class="comment-box">
      <div class="comment-<%= @comment.id %>">
        <%= render 'comments/upvote_button', comment: @comment %>
        <h1 class="comment-body"><%= @comment.body %></h1>
        <%= link_to user_path(@comment.user) do %>
          <span class="comment-user"><i class="fa fa-user"></i> <%= @comment.user.username %></span>
        <% end %>
        <div class="correct-incorrect-scores">
          <span class="correct-guesses"><%= @comment.correct_guesses %> <i class="fa fa-check"></i></span> |
          <span class="incorrect-guesses"><%= @comment.incorrect_guesses %> <i class="fa fa-close"></i></span>
        </div>
        <% if logged_in? && current_user != @comment.user %>
          <% if !@correct_guess %>
            <%= form_for guess, remote: true, html: {class: "guess-form-#{@comment.id}"} do |f| %>
              <%= f.text_field :body, :placeholder  =>  "Guess The Movie" %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :comment_id, :value => @comment.id %>
              <%= f.button :submit, data: { disable_with: "Submitting..." }, class: "radius" %>
            <% end %>
          <% else %>
            <button>Correct</button>
          <% end %>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/comments/upvote.js.erb
var container = $('.upvote-button-partial-<%= @comment.id %>');
container.replaceWith('<%= escape_javascript render "comments/upvote_button", comment: @comment %>');