config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :movies

  get 'more_movies', to: 'movies#more_movies', as: :more_movies

  resources :sessions, only: [:new, :create]

  resources :users

  get 'user_top_posts', to: 'users#top_posts', as: :user_top_posts
  get 'user_new_posts', to: 'users#new_posts', as: :user_new_posts

  resources :comments

  get 'upvote', to: 'comments#upvote', as: :upvote

  resources :home, only: [:index]

  get 'top_posts', to: 'home#top_posts', as: :top_posts
  get 'my_posts', to: 'home#my_posts', as: :my_posts
  get 'new_posts', to: 'home#new_posts', as: :new_posts
  get 'my_correct_guesses', to: 'home#my_correct_guesses', as: :my_correct_guesses

  resources :guesses

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, uniqueness: true, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :username, uniqueness: true

  has_many :comments
  has_many :guesses

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to home_index_path
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.order("created_at desc").take(20)
    @guess = Guess.new
  end

  def new_posts
    @user = User.find(params[:id])
    @comments = @user.comments.order("created_at desc").take(20)
    @guess = Guess.new
  end

  def top_posts
    @user = User.find(params[:id])
    @comments = @user.comments.order("cached_votes_up desc").take(20)
    @guess = Guess.new
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, required: true %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, required: true %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, required: true %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, required: true %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
<br>
<br>
Already Have An Account?
<button><%= link_to "Login", new_session_path %></button>

app/views/users/new_posts.js.erb
var container = $('.emovi-list-partial');
container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments, guess: @guess %>');

app/views/users/show.html.erb
<section class="hero">
  <div class="row intro">
    <div class="medium-centered medium-12 columns">
      <h1><strong>Emovi</strong></h1>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="registration-buttons medium-4 small-12 small-centered columns">
      <div class="small-6 columns">
        <%= link_to new_user_path do %>
          <button class="expand radius">Sign Up</button>
        <% end %>
      </div>
      <div class="small-6 columns">
        <%= link_to new_session_path do %>
          <button class="expand radius">Sign In</button>
        <% end %>
      </div>
    </div>
  <% end %>
</section>

<div class="row">
  <div class="small-9 small-centered columns">
    <h1><%= @user.username %></h1>
    <h1>Sort:</h1>
    <%= link_to user_new_posts_path(params: {id: @user.id}), remote: true do %>
      <button class="tiny radius">New</button>
    <% end %>
    <%= link_to user_top_posts_path(params: {id: @user.id}), remote: true do %>
      <button class="tiny radius">Top</button>
    <% end %>
  </div>
  <%= render 'comments/list', comments: @comments, guess: @guess  %>
</div>

app/views/users/top_posts.js.erb
var container = $('.emovi-list-partial');
container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments, guess: @guess %>');