config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :movies

  get 'more_movies', to: 'movies#more_movies', as: :more_movies

  resources :sessions, only: [:new, :create]

  resources :users

  get 'user_top_posts', to: 'users#top_posts', as: :user_top_posts
  get 'user_new_posts', to: 'users#new_posts', as: :user_new_posts

  resources :comments

  get 'upvote', to: 'comments#upvote', as: :upvote

  resources :home, only: [:index]

  get 'top_posts', to: 'home#top_posts', as: :top_posts
  get 'my_posts', to: 'home#my_posts', as: :my_posts
  get 'new_posts', to: 'home#new_posts', as: :new_posts
  get 'my_correct_guesses', to: 'home#my_correct_guesses', as: :my_correct_guesses

  resources :guesses

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.filter_by(1970,10).sample(5)
    if current_user
      @user = current_user
      @correct_guesses = Guess.correct_guesses(current_user.id)
      @comments = Comment.all.order("created_at desc").take(20)
      @correct_guesses.each do |cg|
        @comments = @comments.reject do |comment|
          (comment.id == cg.comment_id)
        end
      end
      @guess = Guess.new
    else
      @comments = Comment.all.order("created_at desc").take(20)
    end
  end

  def top_posts
    if current_user
      @user = current_user
      @correct_guesses = Guess.correct_guesses(current_user.id)
      @comments = Comment.order("cached_votes_up desc").take(20)
      @correct_guesses.each do |cg|
        @comments = @comments.reject { |comment| (comment.id == cg.comment_id) }
      end
      @guess = Guess.new
    else
      @comments = Comment.order("cached_votes_up desc").take(20)
    end
  end

  def my_posts
    @comments = Comment.user_comments(params[:u_id])
  end

  def new_posts
    if current_user
      @user = current_user
      @correct_guesses = Guess.correct_guesses(current_user.id)
      @comments = Comment.all.order("created_at desc").take(20)
      @correct_guesses.each do |cg|
        @comments = @comments.reject { |comment| (comment.id == cg.comment_id) }
      end
      @guess = Guess.new
    else
      @comments = Comment.all.order("created_at desc").take(20)
    end
  end

  def my_correct_guesses
    @comments = Comment.guessed_correctly(params[:u_id]).includes(:guesses).joins(:guesses).order("guesses.created_at desc")
    @correct_guess = true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="hero">
  <div class="row intro">
    <div class="medium-centered medium-12 columns">
      <h1><strong>Emovi</strong></h1>
    </div>
  </div>
  <% if !logged_in? %>
    <div class="registration-buttons medium-4 small-12 small-centered columns">
      <div class="small-6 columns">
        <%= link_to new_user_path do %>
          <button class="expand radius">Sign Up</button>
        <% end %>
      </div>
      <div class="small-6 columns">
        <%= link_to new_session_path do %>
          <button class="expand radius">Sign In</button>
        <% end %>
      </div>
    </div>
  <% end %>
</section>

<div class="row">
  <div class="small-9 small-centered columns">
    <h1>Movies</h1><%= link_to "More Movies", more_movies_path, remote: true %>
    <%= render 'movies/button_list', movies: @movies %>
    <h1>Sort:</h1>
    <%= link_to new_posts_path, remote: true do %>
      <button class="tiny radius">New</button>
    <% end %>
    <%= link_to top_posts_path, remote: true do %>
      <button class="tiny radius">Top</button>
    <% end %>
    <% if logged_in? %>
      <%= link_to my_posts_path(params: { u_id: current_user.id }), remote: true do %>
        <button class="tiny radius">My Posts</button>
      <% end %>
      <%= link_to my_correct_guesses_path(params: { u_id: current_user.id }), remote: true do %>
        <button class="tiny radius">Previously Guessed</button>
      <% end %>
    <% end %>
  </div>
  <%= render 'comments/list', comments: @comments, guess: @guess  %>

</div>

<div id="movieListModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <% @movies.each do |movie| %>
    <h2 id="modalTitle"><%= movie.title %></h2>
  <% end %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

app/views/home/my_correct_guesses.js.erb
<% if @comments.present? %>
  var container = $('.emovi-list-partial');
  container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments %>');
<% else %>
  var container = $('.emovi-list-partial');
  container.prepend('<h1>No Correct Guesses</h1>');
<% end %>

app/views/home/my_posts.js.erb
<% if @comments.present? %>
  var container = $('.emovi-list-partial');
  container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments %>');
<% else %>
  var container = $('.emovi-list-partial');
  container.prepend('<h1>No Posts</h1>');
<% end %>

app/views/home/new_posts.js.erb
var container = $('.emovi-list-partial');
container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments, guess: @guess %>');

app/views/home/top_posts.js.erb
var container = $('.emovi-list-partial');
container.replaceWith('<%= escape_javascript render "comments/list", comments: @comments, guess: @guess %>');